/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Remotepay {

    public class QueryStatusEnum: Codable {

        public var queryStatus: CLVModels.Remotepay.QueryStatus?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case queryStatus
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self.queryStatus = try rootContainer.decodeIfPresent(CLVModels.Remotepay.QueryStatus.self, forKey: .queryStatus)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (queryStatus != nil) { try container.encode(queryStatus, forKey: .queryStatus) }
        }
    }

}