/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

/*
    Request to start a custom activity on a device.
*/

import Foundation

extension CLVModels.Remotepay {

    public class CustomActivityRequest: Codable {

        /// The superClass
        public var _meta_superclass: CLVModels.Remotepay.BaseRequest?
        /// The name of the action for this activity
        public var action: String?
        /// Data for this activity
        public var payload: String?
        /// If true, then the activity can be stopped in regular execution.
        public var nonBlocking: Bool?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case _meta_superclass
            case action
            case payload
            case nonBlocking
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self._meta_superclass = try rootContainer.decodeIfPresent(CLVModels.Remotepay.BaseRequest.self, forKey: ._meta_superclass)
            } catch {
                decodeError.append(error)
            }
            do {
                self.action = try rootContainer.decodeIfPresent(String.self, forKey: .action)
            } catch {
                decodeError.append(error)
            }
            do {
                self.payload = try rootContainer.decodeIfPresent(String.self, forKey: .payload)
            } catch {
                decodeError.append(error)
            }
            do {
                self.nonBlocking = try rootContainer.decodeIfPresent(Bool.self, forKey: .nonBlocking)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (_meta_superclass != nil) { try container.encode(_meta_superclass, forKey: ._meta_superclass) }
            if (action != nil) { try container.encode(action, forKey: .action) }
            if (payload != nil) { try container.encode(payload, forKey: .payload) }
            if (nonBlocking != nil) { try container.encode(nonBlocking, forKey: .nonBlocking) }
        }
    }

}