/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Remotepay {

    public class VoidPaymentRefundRequest: Codable {

        /// The superClass
        public var _meta_superclass: CLVModels.Remotepay.BaseRequest?
        /// Unique identifier
        public var refundId: String?
        /// Unique identifier
        public var orderId: String?
        /// Unique identifier
        public var employeeId: String?
        /// If true, then do not print using the clover printer.  Return print information.
        public var disablePrinting: CLVModels.Variant?
        /// Do not show the receipt options screen
        public var disableReceiptSelection: CLVModels.Variant?
        /// Extra pass-through data used by external systems.
        public var extras: [String:String]?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case _meta_superclass
            case refundId
            case orderId
            case employeeId
            case disablePrinting
            case disableReceiptSelection
            case extras
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self._meta_superclass = try rootContainer.decodeIfPresent(CLVModels.Remotepay.BaseRequest.self, forKey: ._meta_superclass)
            } catch {
                decodeError.append(error)
            }
            do {
                self.refundId = try rootContainer.decodeIfPresent(String.self, forKey: .refundId)
            } catch {
                decodeError.append(error)
            }
            do {
                self.orderId = try rootContainer.decodeIfPresent(String.self, forKey: .orderId)
            } catch {
                decodeError.append(error)
            }
            do {
                self.employeeId = try rootContainer.decodeIfPresent(String.self, forKey: .employeeId)
            } catch {
                decodeError.append(error)
            }
            do {
                self.disablePrinting = try rootContainer.decodeIfPresent(CLVModels.Variant.self, forKey: .disablePrinting)
            } catch {
                decodeError.append(error)
            }
            do {
                self.disableReceiptSelection = try rootContainer.decodeIfPresent(CLVModels.Variant.self, forKey: .disableReceiptSelection)
            } catch {
                decodeError.append(error)
            }
            do {
                self.extras = try rootContainer.decodeIfPresent([String:String].self, forKey: .extras)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (_meta_superclass != nil) { try container.encode(_meta_superclass, forKey: ._meta_superclass) }
            if (refundId != nil) { try container.encode(refundId, forKey: .refundId) }
            if (orderId != nil) { try container.encode(orderId, forKey: .orderId) }
            if (employeeId != nil) { try container.encode(employeeId, forKey: .employeeId) }
            if (disablePrinting != nil) { try container.encode(disablePrinting, forKey: .disablePrinting) }
            if (disableReceiptSelection != nil) { try container.encode(disableReceiptSelection, forKey: .disableReceiptSelection) }
            if (extras != nil) { try container.encode(extras, forKey: .extras) }
        }
    }

}