/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

extension CLVModels.Ecomm {

    public enum item_type: Codable {
        case sku
        case tax
        case shipping
        case PARSE_UNKNOWN(String)

        enum Key: CodingKey {
            case rawValue
        }

        public init(rawValue:String) {
            switch rawValue {
                case  "sku":
                    self = .sku
                case  "tax":
                    self = .tax
                case  "shipping":
                    self = .shipping
                default:
                    self = .PARSE_UNKNOWN(rawValue)
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self.init(rawValue: rawValue)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(toString)
        }

        public var toString: String {
            switch self {
                case  .sku:
                    return "sku"
                case  .tax:
                    return "tax"
                case  .shipping:
                    return "shipping"
                case .PARSE_UNKNOWN(let rawValue):
                    return rawValue            
            }
        }
    }
}