/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Ecomm {

    public class BillingDetails: Codable {

        /// Full name.
        public var name: CLVModels.Variant?
        /// Email address.
        public var email: CLVModels.Variant?
        /// Billing phone number.
        public var phone: CLVModels.Variant?
        /// Billing address.
        public var address: CLVModels.Ecomm.Address?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case name
            case email
            case phone
            case address
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self.name = try rootContainer.decodeIfPresent(CLVModels.Variant.self, forKey: .name)
            } catch {
                decodeError.append(error)
            }
            do {
                self.email = try rootContainer.decodeIfPresent(CLVModels.Variant.self, forKey: .email)
            } catch {
                decodeError.append(error)
            }
            do {
                self.phone = try rootContainer.decodeIfPresent(CLVModels.Variant.self, forKey: .phone)
            } catch {
                decodeError.append(error)
            }
            do {
                self.address = try rootContainer.decodeIfPresent(CLVModels.Ecomm.Address.self, forKey: .address)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (name != nil) { try container.encode(name, forKey: .name) }
            if (email != nil) { try container.encode(email, forKey: .email) }
            if (phone != nil) { try container.encode(phone, forKey: .phone) }
            if (address != nil) { try container.encode(address, forKey: .address) }
        }
    }

}