/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

extension CLVModels.Ecomm {

    public enum EcommerceIndicator: Codable {
        case ecom
        case moto
        case PARSE_UNKNOWN(String)

        enum Key: CodingKey {
            case rawValue
        }

        public init(rawValue:String) {
            switch rawValue {
                case  "ecom":
                    self = .ecom
                case  "moto":
                    self = .moto
                default:
                    self = .PARSE_UNKNOWN(rawValue)
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self.init(rawValue: rawValue)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(toString)
        }

        public var toString: String {
            switch self {
                case  .ecom:
                    return "ecom"
                case  .moto:
                    return "moto"
                case .PARSE_UNKNOWN(let rawValue):
                    return rawValue            
            }
        }
    }
}