/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

extension CLVModels.Customers {

    public enum TokenType: Codable {
        case MULTIPAY
        case FINANCIAL
        case CTOKEN
        case PARSE_UNKNOWN(String)

        enum Key: CodingKey {
            case rawValue
        }

        public init(rawValue:String) {
            switch rawValue {
                case  "MULTIPAY":
                    self = .MULTIPAY
                case  "FINANCIAL":
                    self = .FINANCIAL
                case  "CTOKEN":
                    self = .CTOKEN
                default:
                    self = .PARSE_UNKNOWN(rawValue)
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self.init(rawValue: rawValue)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(toString)
        }

        public var toString: String {
            switch self {
                case  .MULTIPAY:
                    return "MULTIPAY"
                case  .FINANCIAL:
                    return "FINANCIAL"
                case  .CTOKEN:
                    return "CTOKEN"
                case .PARSE_UNKNOWN(let rawValue):
                    return rawValue            
            }
        }
    }
}