/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Inventory {

    public class MenuModifierGroup: Codable {

        /// Modifier group id
        public var id: String?
        /// Reference to the modifier group
        public var modifierGroup: CLVModels.Base.Reference?
        /// Reference to the merchant that created the item
        public var merchantRef: CLVModels.Base.Reference?
        /// Customer facing modifier group name
        public var name: String?
        /// Modifier group description
        public var description_: String?
        /// The minimum amount of modifiers from this group that must be applied to associated lineItems
        public var minRequired: CLVModels.Variant?
        /// The maximum amount of modifiers from this group that can be applied to associated lineItems
        public var maxAllowed: CLVModels.Variant?
        /// Reason for being filtered out
        public var reasonCode: String?
        /// If the menu modifier group has been filtered by the filter microservice.
        public var filtered: Bool?
        /// Modifier group image file path
        public var imageFilename: String?
        /// Modifier group enabled for menu
        public var enabled: Bool?
        /// Timestamp when the menu modifier group was created
        public var createdTime: Date?
        /// Timestamp when the menu modifier group was last modified
        public var modifiedTime: Date?
        /// Timestamp when menu modifier group was last deleted
        public var deletedTime: Date?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case id
            case modifierGroup
            case merchantRef
            case name
            case description
            case minRequired
            case maxAllowed
            case reasonCode
            case filtered
            case imageFilename
            case enabled
            case createdTime
            case modifiedTime
            case deletedTime
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self.id = try rootContainer.decodeIfPresent(String.self, forKey: .id)
            } catch {
                decodeError.append(error)
            }
            do {
                self.modifierGroup = try rootContainer.decodeIfPresent(CLVModels.Base.Reference.self, forKey: .modifierGroup)
            } catch {
                decodeError.append(error)
            }
            do {
                self.merchantRef = try rootContainer.decodeIfPresent(CLVModels.Base.Reference.self, forKey: .merchantRef)
            } catch {
                decodeError.append(error)
            }
            do {
                self.name = try rootContainer.decodeIfPresent(String.self, forKey: .name)
            } catch {
                decodeError.append(error)
            }
            do {
                self.description_ = try rootContainer.decodeIfPresent(String.self, forKey: .description)
            } catch {
                decodeError.append(error)
            }
            do {
                self.minRequired = try rootContainer.decodeIfPresent(CLVModels.Variant.self, forKey: .minRequired)
            } catch {
                decodeError.append(error)
            }
            do {
                self.maxAllowed = try rootContainer.decodeIfPresent(CLVModels.Variant.self, forKey: .maxAllowed)
            } catch {
                decodeError.append(error)
            }
            do {
                self.reasonCode = try rootContainer.decodeIfPresent(String.self, forKey: .reasonCode)
            } catch {
                decodeError.append(error)
            }
            do {
                self.filtered = try rootContainer.decodeIfPresent(Bool.self, forKey: .filtered)
            } catch {
                decodeError.append(error)
            }
            do {
                self.imageFilename = try rootContainer.decodeIfPresent(String.self, forKey: .imageFilename)
            } catch {
                decodeError.append(error)
            }
            do {
                self.enabled = try rootContainer.decodeIfPresent(Bool.self, forKey: .enabled)
            } catch {
                decodeError.append(error)
            }
            do {
                self.createdTime = try rootContainer.decodeIfPresent(Date.self, forKey: .createdTime)
            } catch {
                decodeError.append(error)
            }
            do {
                self.modifiedTime = try rootContainer.decodeIfPresent(Date.self, forKey: .modifiedTime)
            } catch {
                decodeError.append(error)
            }
            do {
                self.deletedTime = try rootContainer.decodeIfPresent(Date.self, forKey: .deletedTime)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (id != nil) { try container.encode(id, forKey: .id) }
            if (modifierGroup != nil) { try container.encode(modifierGroup, forKey: .modifierGroup) }
            if (merchantRef != nil) { try container.encode(merchantRef, forKey: .merchantRef) }
            if (name != nil) { try container.encode(name, forKey: .name) }
            if (description_ != nil) { try container.encode(description_, forKey: .description) }
            if (minRequired != nil) { try container.encode(minRequired, forKey: .minRequired) }
            if (maxAllowed != nil) { try container.encode(maxAllowed, forKey: .maxAllowed) }
            if (reasonCode != nil) { try container.encode(reasonCode, forKey: .reasonCode) }
            if (filtered != nil) { try container.encode(filtered, forKey: .filtered) }
            if (imageFilename != nil) { try container.encode(imageFilename, forKey: .imageFilename) }
            if (enabled != nil) { try container.encode(enabled, forKey: .enabled) }
            if (createdTime != nil) { try container.encode(createdTime, forKey: .createdTime) }
            if (modifiedTime != nil) { try container.encode(modifiedTime, forKey: .modifiedTime) }
            if (deletedTime != nil) { try container.encode(deletedTime, forKey: .deletedTime) }
        }
    }

}