/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Pay {

    public class PaymentProcessor: Codable {

        public var id: String?
        public var name: String?
        public var paymentGatewayApi: String?
        public var production: Bool?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case id
            case name
            case paymentGatewayApi
            case production
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self.id = try rootContainer.decodeIfPresent(String.self, forKey: .id)
            } catch {
                decodeError.append(error)
            }
            do {
                self.name = try rootContainer.decodeIfPresent(String.self, forKey: .name)
            } catch {
                decodeError.append(error)
            }
            do {
                self.paymentGatewayApi = try rootContainer.decodeIfPresent(String.self, forKey: .paymentGatewayApi)
            } catch {
                decodeError.append(error)
            }
            do {
                self.production = try rootContainer.decodeIfPresent(Bool.self, forKey: .production)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (id != nil) { try container.encode(id, forKey: .id) }
            if (name != nil) { try container.encode(name, forKey: .name) }
            if (paymentGatewayApi != nil) { try container.encode(paymentGatewayApi, forKey: .paymentGatewayApi) }
            if (production != nil) { try container.encode(production, forKey: .production) }
        }
    }

}