/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Payments {

    public class FraudResponseReason: Codable {

        public var action: CLVModels.Payments.FraudResponseAction?
        /// Rule that triggered this action
        public var ruleTriggered: String?
        /// Human readable reason associated with the rule
        public var reason: String?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case action
            case ruleTriggered
            case reason
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self.action = try rootContainer.decodeIfPresent(CLVModels.Payments.FraudResponseAction.self, forKey: .action)
            } catch {
                decodeError.append(error)
            }
            do {
                self.ruleTriggered = try rootContainer.decodeIfPresent(String.self, forKey: .ruleTriggered)
            } catch {
                decodeError.append(error)
            }
            do {
                self.reason = try rootContainer.decodeIfPresent(String.self, forKey: .reason)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (action != nil) { try container.encode(action, forKey: .action) }
            if (ruleTriggered != nil) { try container.encode(ruleTriggered, forKey: .ruleTriggered) }
            if (reason != nil) { try container.encode(reason, forKey: .reason) }
        }
    }

}