/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

extension CLVModels.Payments {

    public enum PcTaxIndicator: Codable {
        case UNKNOWN
        case TAXABLE
        case NON_TAXABLE
        case PARSE_UNKNOWN(String)

        enum Key: CodingKey {
            case rawValue
        }

        public init(rawValue:String) {
            switch rawValue {
                case  "UNKNOWN":
                    self = .UNKNOWN
                case  "TAXABLE":
                    self = .TAXABLE
                case  "NON_TAXABLE":
                    self = .NON_TAXABLE
                default:
                    self = .PARSE_UNKNOWN(rawValue)
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self.init(rawValue: rawValue)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(toString)
        }

        public var toString: String {
            switch self {
                case  .UNKNOWN:
                    return "UNKNOWN"
                case  .TAXABLE:
                    return "TAXABLE"
                case  .NON_TAXABLE:
                    return "NON_TAXABLE"
                case .PARSE_UNKNOWN(let rawValue):
                    return rawValue            
            }
        }
    }
}