/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

extension CLVModels.Payments {

    public enum ReversalReason: Codable {
        case CHIP_DECLINE
        case CARDHOLDER_CANCELLATION
        case COMMUNICATION_ERROR
        case OTHER_REASON
        case PARSE_UNKNOWN(String)

        enum Key: CodingKey {
            case rawValue
        }

        public init(rawValue:String) {
            switch rawValue {
                case  "CHIP_DECLINE":
                    self = .CHIP_DECLINE
                case  "CARDHOLDER_CANCELLATION":
                    self = .CARDHOLDER_CANCELLATION
                case  "COMMUNICATION_ERROR":
                    self = .COMMUNICATION_ERROR
                case  "OTHER_REASON":
                    self = .OTHER_REASON
                default:
                    self = .PARSE_UNKNOWN(rawValue)
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self.init(rawValue: rawValue)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(toString)
        }

        public var toString: String {
            switch self {
                case  .CHIP_DECLINE:
                    return "CHIP_DECLINE"
                case  .CARDHOLDER_CANCELLATION:
                    return "CARDHOLDER_CANCELLATION"
                case  .COMMUNICATION_ERROR:
                    return "COMMUNICATION_ERROR"
                case  .OTHER_REASON:
                    return "OTHER_REASON"
                case .PARSE_UNKNOWN(let rawValue):
                    return rawValue            
            }
        }
    }
}