/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Remotemessage {

    public class RemoveDiscountAction: Codable {

        public var discountId: String?
        public var lineItemId: String?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case discountId
            case lineItemId
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self.discountId = try rootContainer.decodeIfPresent(String.self, forKey: .discountId)
            } catch {
                decodeError.append(error)
            }
            do {
                self.lineItemId = try rootContainer.decodeIfPresent(String.self, forKey: .lineItemId)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (discountId != nil) { try container.encode(discountId, forKey: .discountId) }
            if (lineItemId != nil) { try container.encode(lineItemId, forKey: .lineItemId) }
        }
    }

}