/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Order {

    public class DisplayDiscount: Codable {

        /// Unique identifier
        public var id: String?
        /// The lineItem with which the discount is associated
        public var lineItemId: String?
        /// Name of the discount
        public var name: String?
        /// Formatted discount amount
        public var amount: String?
        /// Discount amount in percent
        public var percentage: String?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case id
            case lineItemId
            case name
            case amount
            case percentage
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self.id = try rootContainer.decodeIfPresent(String.self, forKey: .id)
            } catch {
                decodeError.append(error)
            }
            do {
                self.lineItemId = try rootContainer.decodeIfPresent(String.self, forKey: .lineItemId)
            } catch {
                decodeError.append(error)
            }
            do {
                self.name = try rootContainer.decodeIfPresent(String.self, forKey: .name)
            } catch {
                decodeError.append(error)
            }
            do {
                self.amount = try rootContainer.decodeIfPresent(String.self, forKey: .amount)
            } catch {
                decodeError.append(error)
            }
            do {
                self.percentage = try rootContainer.decodeIfPresent(String.self, forKey: .percentage)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (id != nil) { try container.encode(id, forKey: .id) }
            if (lineItemId != nil) { try container.encode(lineItemId, forKey: .lineItemId) }
            if (name != nil) { try container.encode(name, forKey: .name) }
            if (amount != nil) { try container.encode(amount, forKey: .amount) }
            if (percentage != nil) { try container.encode(percentage, forKey: .percentage) }
        }
    }

}