/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

extension CLVModels.Loyalty {

    public enum CustomerProvidedDataResponseType: Codable {
        case ACCEPTED
        case PENDING
        case PARSE_UNKNOWN(String)

        enum Key: CodingKey {
            case rawValue
        }

        public init(rawValue:String) {
            switch rawValue {
                case  "ACCEPTED":
                    self = .ACCEPTED
                case  "PENDING":
                    self = .PENDING
                default:
                    self = .PARSE_UNKNOWN(rawValue)
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self.init(rawValue: rawValue)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(toString)
        }

        public var toString: String {
            switch self {
                case  .ACCEPTED:
                    return "ACCEPTED"
                case  .PENDING:
                    return "PENDING"
                case .PARSE_UNKNOWN(let rawValue):
                    return rawValue            
            }
        }
    }
}