/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


import Foundation

extension CLVModels.Merchant {

    public class TipSuggestion: Codable {

        public var id: String?
        /// Name of the tip
        public var name: String?
        /// Suggested tip percentage
        public var percentage: Int64?
        /// Suggested tip amount
        public var amount: Int64?
        public var isEnabled: Bool?

        public var decodeError:[Swift.Error] = [Swift.Error]()

        enum CodingKeys: CodingKey {
            case id
            case name
            case percentage
            case amount
            case isEnabled
        }

        public init() {}

        required public init(from decoder: Decoder) throws {
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            do {
                self.id = try rootContainer.decodeIfPresent(String.self, forKey: .id)
            } catch {
                decodeError.append(error)
            }
            do {
                self.name = try rootContainer.decodeIfPresent(String.self, forKey: .name)
            } catch {
                decodeError.append(error)
            }
            do {
                self.percentage = try rootContainer.decodeIfPresent(Int64.self, forKey: .percentage)
            } catch {
                decodeError.append(error)
            }
            do {
                self.amount = try rootContainer.decodeIfPresent(Int64.self, forKey: .amount)
            } catch {
                decodeError.append(error)
            }
            do {
                self.isEnabled = try rootContainer.decodeIfPresent(Bool.self, forKey: .isEnabled)
            } catch {
                decodeError.append(error)
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            if (id != nil) { try container.encode(id, forKey: .id) }
            if (name != nil) { try container.encode(name, forKey: .name) }
            if (percentage != nil) { try container.encode(percentage, forKey: .percentage) }
            if (amount != nil) { try container.encode(amount, forKey: .amount) }
            if (isEnabled != nil) { try container.encode(isEnabled, forKey: .isEnabled) }
        }
    }

}