/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

extension CLVModels.Hours {

    public enum ReferenceType: Codable {
        case ORDER_TYPE
        case ITEM_GROUP
        case SOFTWARE_UPDATE_EXCLUSION
        case ONLINE_ORDER_SERVICE
        case PARSE_UNKNOWN(String)

        enum Key: CodingKey {
            case rawValue
        }

        public init(rawValue:String) {
            switch rawValue {
                case  "ORDER_TYPE":
                    self = .ORDER_TYPE
                case  "ITEM_GROUP":
                    self = .ITEM_GROUP
                case  "SOFTWARE_UPDATE_EXCLUSION":
                    self = .SOFTWARE_UPDATE_EXCLUSION
                case  "ONLINE_ORDER_SERVICE":
                    self = .ONLINE_ORDER_SERVICE
                default:
                    self = .PARSE_UNKNOWN(rawValue)
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self.init(rawValue: rawValue)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(toString)
        }

        public var toString: String {
            switch self {
                case  .ORDER_TYPE:
                    return "ORDER_TYPE"
                case  .ITEM_GROUP:
                    return "ITEM_GROUP"
                case  .SOFTWARE_UPDATE_EXCLUSION:
                    return "SOFTWARE_UPDATE_EXCLUSION"
                case  .ONLINE_ORDER_SERVICE:
                    return "ONLINE_ORDER_SERVICE"
                case .PARSE_UNKNOWN(let rawValue):
                    return rawValue            
            }
        }
    }
}