/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

extension CLVModels.Device {

    public enum DeviceProvisionState: Codable {
        case NOT_ASSOCIATED
        case DISASSOCIATED
        case ASSOCIATED
        case PARSE_UNKNOWN(String)

        enum Key: CodingKey {
            case rawValue
        }

        public init(rawValue:String) {
            switch rawValue {
                case  "NOT_ASSOCIATED":
                    self = .NOT_ASSOCIATED
                case  "DISASSOCIATED":
                    self = .DISASSOCIATED
                case  "ASSOCIATED":
                    self = .ASSOCIATED
                default:
                    self = .PARSE_UNKNOWN(rawValue)
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(String.self)
            self.init(rawValue: rawValue)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            try container.encode(toString)
        }

        public var toString: String {
            switch self {
                case  .NOT_ASSOCIATED:
                    return "NOT_ASSOCIATED"
                case  .DISASSOCIATED:
                    return "DISASSOCIATED"
                case  .ASSOCIATED:
                    return "ASSOCIATED"
                case .PARSE_UNKNOWN(let rawValue):
                    return rawValue            
            }
        }
    }
}